### ISSUE TITLE
nevergrad

### ISSUE THREAD

**Issue by teytaud** [daxiongshu/rapids-ai-BBO-2nd-place-solution#8] opened 2021-04-29 15:50 UTC
Hello, your article mentions Nevergrad as an optimization algorithm, but there are dozens of optimization methods in Nevergrad. Could you tell us which one you have tried ?

https://arxiv.org/pdf/2012.04201.pdf

Have a great day :-)

**Comment by teytaud** [comment] 2021-04-29 15:52
(in particular I fail to find Nevergrad in your code so I can't check ?)

**Comment by teytaud** [comment] 2021-04-29 16:10
In particular it turns out that Isabelle Guyon has shared a code with a buggy line using a random search instead of Nevergrad ("OnePlusOne" instead of "NgOpt") and obviously it performs very poorly. Various people have copy-pasted this and this is not good for the reputation of Nevergrad which does work much better than random search :-)

**Comment by daxiongshu** [comment] 2021-08-02 17:52
Hello @teytaud, thank you for raising this issue. I'm very sorry for the late response. Yeah, we just used the code in the [competition starter kit](https://github.com/rdturnermtl/bbo_challenge_starter_kit/) so it is caused by the bug.

I just updated our paper where all references of "nevergrad" are replaced by "Random Search". The update will be visible on Tue, 3 Aug 2021 00:00:00 GMT. Please let me know if it is anything else we need to address.

**Comment by daxiongshu** [comment] 2021-08-03 12:52
Hey, the updated paper is online: https://arxiv.org/pdf/2012.04201.pdf
I'll close this issue for now. Please feel free to comment and I'll reopen the issue if necessary. Thank you so much.

**Closed as completed by daxiongshu** 2021-08-03 12:52 UTC
